name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "c64da566-9347-4950-9c17-03cf00954183" \
            --password "p.18Q~GAZKCc3zuRdoezNTEiBavH9LN.wDvE4aB3" \
            --tenant "f1443a2a-8429-4f97-8a40-b3021908fc59"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "83d4cba0-c6b0-4b71-8050-0b7fd5ba5202"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "c64da566-9347-4950-9c17-03cf00954183" \
            --password "p.18Q~GAZKCc3zuRdoezNTEiBavH9LN.wDvE4aB3" \
            --tenant "f1443a2a-8429-4f97-8a40-b3021908fc59"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "83d4cba0-c6b0-4b71-8050-0b7fd5ba5202"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
